version: '3.8'
services:
  parallaxmd-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parallaxmd-marketing
    restart: unless-stopped
    expose:
      - "3310"
    environment:
      - NODE_ENV=production
    networks:
      - net

networks:
  net:
    external: true
